serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::111122223333:role/my-role

stateStore:
  dataDirectory: "prefix/of/data"
  s3:
    enabled: true
    region: us-east-1
    bucket: risingwave
    authentication:
      useServiceAccount: true
