stateStore:
  dataDirectory: "prefix/of/data"
  obs:
    enabled: true
    region: us-east-1
    bucket: risingwave
    authentication:
      useServiceAccount: false
      accessKey: ak
      secretAccessKey: sk
