{{/*
Copyright RisingWave Labs.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{ if and (not .Values.standalone.enabled ) (.Values.icebergCompactorComponent.enabled) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "risingwave.icebergCompactorComponentName" . }}
  labels:
    {{- include "risingwave.labels" . | nindent 4 }}
    risingwave.risingwavelabs.com/component: iceberg-compactor
  {{- $annotations := (include "risingwave.annotations" . ) | trim }}
  {{- if $annotations }}
  annotations:
    {{ nindent 4 $annotations }}
  {{- end }}
spec:
  replicas: {{ .Values.icebergCompactorComponent.replicas }}
  selector:
    matchLabels:
      {{- include "risingwave.selectorLabels" . | nindent 6 }}
      risingwave.risingwavelabs.com/component: iceberg-compactor
  strategy:
    type: Recreate
  minReadySeconds: 0
  template:
    metadata:
      labels:
        {{- include "risingwave.selectorLabels" . | nindent 8 }}
        risingwave.risingwavelabs.com/component: iceberg-compactor
        risingwave/name: {{ include "risingwave.fullname" . }}
        risingwave/component: iceberg-compactor
        {{- if .Values.icebergCompactorComponent.podLabels }}
        {{- toYaml .Values.icebergCompactorComponent.podLabels | nindent 8 }}
        {{- end }}
      annotations:
        {{- if .Values.monitor.annotations.enabled }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.ports.compactor.metrics }}"
        prometheus.io/path: "/metrics"
        {{- end }}
        {{- include "risingwave.annotations" . | nindent 8 }}
        {{- if .Values.icebergCompactorComponent.podAnnotations }}
        {{- toYaml .Values.icebergCompactorComponent.podAnnotations | nindent 8 }}
        {{- end }}
        {{- include "risingwave.compactorConfigHashAnnotation" . | nindent 8 }}
    spec:
      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.pullSecrets }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
      volumes:
      - name: config
        configMap:
          name: {{ include "risingwave.configurationConfigMapName" . }}
      {{- if .Values.icebergCompactorComponent.extraVolumes }}
      {{- toYaml .Values.icebergCompactorComponent.extraVolumes | nindent 6 }}
      {{- end }}
      restartPolicy: Always
      {{- if .Values.icebergCompactorComponent.terminationGracePeriodSeconds }}
      terminationGracePeriodSeconds: {{ .Values.icebergCompactorComponent.terminationGracePeriodSeconds }}
      {{- end }}
      {{- if .Values.icebergCompactorComponent.nodeSelector }}
      nodeSelector:
      {{- toYaml .Values.icebergCompactorComponent.nodeSelector | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "risingwave.serviceAccountName" . }}
      automountServiceAccountToken: true
      hostNetwork: false
      hostPID: false
      hostIPC: false
      {{- if .Values.icebergCompactorComponent.shareProcessNamespace }}
      shareProcessNamespace: {{ .Values.icebergCompactorComponent.shareProcessNamespace }}
      {{- end }}
      {{- if .Values.icebergCompactorComponent.podSecurityContext }}
      securityContext: {{- toYaml .Values.icebergCompactorComponent.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.icebergCompactorComponent.affinity }}
      affinity: {{- toYaml .Values.icebergCompactorComponent.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.icebergCompactorComponent.schedulerName }}
      schedulerName: {{ .Values.icebergCompactorComponent.schedulerName }}
      {{- end }}
      {{- if .Values.icebergCompactorComponent.tolerations }}
      tolerations: {{- toYaml .Values.icebergCompactorComponent.tolerations | nindent 8 }}
      {{- end }}
      {{- if .Values.icebergCompactorComponent.priorityClassName }}
      priorityClassName: {{ .Values.icebergCompactorComponent.priorityClassName }}
      {{- end }}
      {{- if .Values.icebergCompactorComponent.runtimeClassName }}
      runtimeClassName: {{ .Values.icebergCompactorComponent.runtimeClassName }}
      {{- end }}
      enableServiceLinks: false
      preemptionPolicy: PreemptLowerPriority
      setHostnameAsFQDN: false
      containers:
      - name: compactor
        image: {{ include "risingwave.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.diagnosticMode.enabled }}
        command: {{ toYaml .Values.diagnosticMode.command | nindent 8 }}
        args: {{ toYaml .Values.diagnosticMode.args | nindent 8 }}
        {{- else }}
        command:
        - /risingwave/bin/risingwave
        - compactor-node
        {{- end }}
        ports:
        - containerPort: {{ .Values.ports.compactor.svc }}
          name: svc
          protocol: TCP
        - containerPort: {{ .Values.ports.compactor.metrics }}
          name: metrics
          protocol: TCP
        envFrom:
        {{- if .Values.icebergCompactorComponent.extraEnvVarsConfigMap }}
        - configMapRef:
            name: {{ .Values.icebergCompactorComponent.extraEnvVarsConfigMap }}
        {{- end }}
        {{- if .Values.icebergCompactorComponent.extraEnvVarsSecret }}
        - secretRef:
            name: {{ .Values.icebergCompactorComponent.extraEnvVarsSecret }}
        {{- end }}
        {{- $credentialsSecret := (include "risingwave.credentialsSecretName" . ) -}}
        {{- if $credentialsSecret }}
        - secretRef:
            name: {{ $credentialsSecret }}
        {{- end }}
        env:
        {{ include "risingwave.cloudEnvironments" . | nindent 8 }}
        # Disable auto region loading. Refer to the original source for more information.
        # https://github.com/awslabs/aws-sdk-rust/blob/main/sdk/aws-config/src/imds/region.rs
        - name: AWS_EC2_METADATA_DISABLED
          value: "true"
        - name: RUST_LOG
          value: {{ .Values.icebergCompactorComponent.rustLog }}
        - name: RUST_BACKTRACE
          value: {{ .Values.icebergCompactorComponent.rustBacktrace }}
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: "status.podIP"
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: "metadata.name"
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        - name: CONTAINER_CPU_LIMIT
          valueFrom:
            resourceFieldRef:
              resource: "limits.cpu"
        - name: CONTAINER_MEMORY_LIMIT
          valueFrom:
            resourceFieldRef:
              resource: "limits.memory"
        - name: RUST_MIN_STACK
          value: "4194304"
        {{- if .Values.stateStore.s3.enabled }}
        - name: AWS_REGION
          value: {{ .Values.stateStore.s3.region }}
        {{- end }}
        {{- if and .Values.stateStore.s3.enabled .Values.stateStore.s3.forcePathStyle }}
        - name: RW_IS_FORCE_PATH_STYLE
          value: 'true'
        {{- end }}
        {{- if .Values.stateStore.oss.enabled }}
        - name: OSS_REGION
          value: {{ .Values.stateStore.oss.region }}
        {{- end }}
        {{- if .Values.stateStore.obs.enabled }}
        - name: OBS_REGION
          value: {{ .Values.stateStore.obs.region }}
        {{- end }}
        {{- if (include "risingwave.bundle.minio.enabled" .) }}
        - name: MINIO_USERNAME
          valueFrom:
            secretKeyRef:
              key: root-user
              name: {{ default (include "common.names.fullname" .Subcharts.minio) .Values.minio.auth.existingSecret }}
        - name: MINIO_PASSWORD
          valueFrom:
            secretKeyRef:
              key: root-password
              name: {{ default (include "common.names.fullname" .Subcharts.minio) .Values.minio.auth.existingSecret }}
        {{- end }}
        {{- if .Values.stateStore.s3.enabled }}
        {{- if .Values.stateStore.s3.endpoint }}
        - name: RW_S3_ENDPOINT
          value: {{ .Values.stateStore.s3.endpoint }}
        {{- end }}
        {{- else if .Values.stateStore.oss.enabled }}
        - name: OSS_ENDPOINT
          value: {{ include "risingwave.oss.endpoint" . }}
        {{- else if .Values.stateStore.obs.enabled }}
        - name: OBS_ENDPOINT
          value: {{ include "risingwave.obs.endpoint" . }}
        {{- else if .Values.stateStore.azblob.enabled }}
        - name: AZBLOB_ENDPOINT
          value: {{ .Values.stateStore.azblob.endpoint }}
        {{- end }}
        - name: RW_CONFIG_PATH
          value: /risingwave/config/risingwave.iceberg_compactor.toml
        - name: RW_LISTEN_ADDR
          value: "0.0.0.0:{{ .Values.ports.compactor.svc }}"
        - name: RW_ADVERTISE_ADDR
          value: "$(POD_IP):{{ .Values.ports.compactor.svc }}"
        - name: RW_PROMETHEUS_LISTENER_ADDR
          value: "0.0.0.0:{{ .Values.ports.compactor.metrics }}"
        - name: RW_META_ADDR
          value: {{ printf "load-balance+http://%s.%s.svc:%d" (include "risingwave.metaHeadlessServiceName" .) .Release.Namespace (.Values.ports.meta.svc | int)}}
        - name: RW_STATE_STORE
          value: {{ include "risingwave.hummockConnectionString" . }}
        - name: RW_DATA_DIRECTORY
          value: {{ include "risingwave.stateStoreDataDirectory" . }}
        - name: RW_COMPACTOR_MODE
          value: dedicated_iceberg
        {{- if .Values.icebergCompactorComponent.extraEnvVars }}
        {{- .Values.icebergCompactorComponent.extraEnvVars | toYaml | nindent 8 }}
        {{- end }}
        {{- if .Values.icebergCompactorComponent.resources }}
        resources:
          {{- if .Values.icebergCompactorComponent.resources.limits }}
          limits:
            {{ toYaml .Values.icebergCompactorComponent.resources.limits | nindent 12 }}
          {{- end }}
          {{- if .Values.icebergCompactorComponent.resources.requests }}
          requests:
            {{ toYaml .Values.icebergCompactorComponent.resources.requests | nindent 12 }}
          {{- end }}
        {{- end }}
        volumeMounts:
        - mountPath: /risingwave/config
          name: config
          readOnly: true
        {{- if .Values.icebergCompactorComponent.extraVolumeMounts }}
        {{- toYaml .Values.icebergCompactorComponent.extraVolumeMounts | nindent 8 }}
        {{- end }}
        {{- if .Values.icebergCompactorComponent.securityContext }}
        securityContext: {{ toYaml .Values.icebergCompactorComponent.securityContext | nindent 10 }}
        {{- end }}
        {{- if not .Values.diagnosticMode.enabled }}
        startupProbe:
          initialDelaySeconds: 2
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 12
          tcpSocket:
            port: svc
        livenessProbe:
          initialDelaySeconds: 2
          periodSeconds: 10
          tcpSocket:
            port: svc
        readinessProbe:
          initialDelaySeconds: 2
          periodSeconds: 10
          tcpSocket:
            port: svc
        {{- end }}
      {{- if .Values.icebergCompactorComponent.additionalContainers }}
      {{- toYaml .Values.icebergCompactorComponent.additionalContainers | nindent 6 }}
      {{- end }}
{{- end -}}
