{{- $secretName := (include "risingwave.licenseKeySecretName" .) }}
{{- with .Values.license }}
{{/* key != "" && (secret.key == "" || secret.name == "") */}}
{{- if and .key (or (empty .secret.key) (empty .secret.name)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
stringData:
  license.jwt: {{ .key }}
{{- end }}
{{- end }}
