{{- $secretName := (include "risingwave.licenseKeySecretName" .) }}
{{- with .Values.license }}
{{/* passAsFile && key != "" && (secret.key == "" || secret.name == "") */}}
{{- if and .passAsFile .key (or (empty .secret.key) (empty .secret.name)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
stringData:
  license.jwt: {{ .key }}
{{- end }}
{{- end }}
