{{/*
Copyright RisingWave Labs
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if and (not .Values.tags.minio) .Values.stateStore.minio.enabled }}
{{- if empty .Values.stateStore.minio.authentication.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "risingwave.minioCredentialsSecretName" . }}
  labels:
    {{- include "risingwave.labels" . | nindent 4 }}
  {{- $annotations := (include "risingwave.annotations" . ) | trim }}
  {{- if $annotations }}
  annotations:
    {{ nindent 4 $annotations }}
  {{- end }}
stringData:
  MINIO_USERNAME: {{ .Values.stateStore.minio.authentication.username }}
  MINIO_PASSWORD: {{ .Values.stateStore.minio.authentication.password }}
{{- end }}
{{- end }}