{{- $secretName := (include "risingwave.secretStoreSecretName" .) }}
{{- $namespace := .Release.Namespace }}
{{- with .Values.secretStore.privateKey }}
{{- if or (empty .secretRef.name) (empty .secretRef.key) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
stringData:
  {{- if .value }}
  privateKey: {{ .value }}
  {{- else }}
  {{- if (lookup "v1" "Secret" $namespace $secretName).data }}
  privateKey: {{ (index (lookup "v1" "Secret" $namespace $secretName).data "privateKey") | b64dec }}
  {{- else }}
  privateKey: {{ (include "randHex" 32 ) | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
