{{/*
Copyright RisingWave Labs.
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "risingwave.serviceAccountName" . }}
  labels:
    {{- include "risingwave.labels" . | nindent 4 }}
    {{- with.Values.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if or (include "risingwave.annotations" .) .Values.serviceAccount.annotations }}
  annotations:
    {{- $annotations := (include "risingwave.annotations" . ) | trim }}
    {{- if $annotations }}
    {{ nindent 4 $annotations }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
