{{/*
Copyright RisingWave Labs
SPDX-License-Identifier: APACHE-2.0
*/}}

{{/*
Validate state store backends.
*/}}
{{- $count := 0 -}}
{{- $name := "" }}
# Count without MinIO.
{{- with .Values.stateStore }}
  {{- if .s3.enabled }}{{ $count = add1 $count }}{{ $name = "S3" }}{{- end }}
  {{- if .gcs.enabled }}{{ $count = add1 $count }}{{ $name = "GCS" }}{{- end }}
  {{- if .oss.enabled }}{{ $count = add1 $count }}{{ $name = "OSS" }}{{- end }}
  {{- if .azblob.enabled }}{{ $count = add1 $count }}{{ $name = "AZBLOB" }}{{- end }}
  {{- if .hdfs.enabled }}{{ $count = add1 $count }}{{ $name = "HDFS" }}{{- end }}
  {{- if .obs.enabled }}{{ $count = add1 $count }}{{ $name = "OBS" }}{{- end }}
  {{- if .localFs.enabled }}{{ $count = add1 $count }}{{ $name = "LocalFS" }}{{- end }}
{{- end }}
# If there's no state store and bundled minio enabled, count = 1
{{- if (include "risingwave.bundle.minio.enabled" .) }}
  {{- if and (eq $count 0) }}
    {{ $count = add1 $count }}
    {{ $name = "MinIO" }}
  {{- else }}
    {{- printf "Unnecessary bundled minio when %s is enabled! Try setting `tags.minio=false,tags.bundle=false` and retry!" $name | fail }}
  {{- end }}
{{- else }}
  {{- if .Values.stateStore.minio.enabled }}{{ $count = add1 $count }}{{ $name = "MinIO" }}{{- end }}
{{- end }}
{{- if (eq $count 0 ) }}
  {{- fail "No state store backend!\n  Please set up one of the backends under `stateStore`, or use the bundled MinIO by setting `tags.minio=true`!" }}
{{- else if (gt $count 1) }}
  {{- fail "More than one state store backends!" }}
{{- end }}

{{/*
Validate the embedded MinIO.
*/}}
{{- if (include "risingwave.bundle.minio.enabled" .) }}
  {{- if empty .Values.minio.defaultBuckets }}
    {{- fail "Set at least one bucket in `minio.defaultBuckets`!" }}
  {{- end }}
{{- end }}

{{/*
Validate meta store backends.
*/}}
{{- $count = 0 -}}
{{- $name = "" }}
# Count without postgresql.
{{- with .Values.metaStore }}
{{- if .sqlite.enabled }}{{ $count = add1 $count }}{{ $name = "sqlite" }}{{- end }}
{{- if .mysql.enabled }}{{ $count = add1 $count }}{{ $name = "mysql" }}{{- end }}
{{- end }}
# If there's no meta store and bundled postgresql enabled, count = 1
{{- if (include "risingwave.bundle.postgresql.enabled" .) }}
  {{- if and (eq $count 0) }}
    {{ $count = add1 $count }}
    {{ $name = "postgresql" }}
  {{- else }}
    {{- printf "Unnecessary bundled postgresql when %s is enabled!" $name | fail }}
  {{- end }}
{{- else }}
  {{- if .Values.metaStore.postgresql.enabled }}{{ $count = add1 $count }}{{ $name = "postgresql" }}{{- end }}
{{- end }}
{{- if (eq $count 0 ) }}
  {{- fail "No meta store backend!\n  Please set up one of the backends under `metaStore`, or use the bundled one by setting `tags.postgresql=true`!" }}
{{- else if (gt $count 1) }}
  {{- fail "More than one meta store backends!" }}
{{- end }}


{{/*
Validate parameters of sqlite meta store.
*/}}
{{- if .Values.metaStore.sqlite.enabled }}
  {{- if empty .Values.metaStore.sqlite.path }}
    {{- fail "DB path .metaStore.sqlite.path must be set!" }}
  {{- end }}
{{- end }}

{{/*
Validate parameters of PostgreSQL meta store.
*/}}
{{- if not (include "risingwave.bundle.postgresql.enabled" .) }}
{{- if .Values.metaStore.postgresql.enabled }}
  {{- if empty .Values.metaStore.postgresql.host }}
    {{- fail "Host .metaStore.postgresql.host must be set!" }}
  {{- end }}
  {{- if empty .Values.metaStore.postgresql.port }}
    {{- fail "Port .metaStore.postgresql.port must be set!" }}
  {{- end }}
  {{- if empty .Values.metaStore.postgresql.database }}
    {{- fail "Database .metaStore.postgresql.database must be set!" }}
  {{- end }}
  {{- with .Values.metaStore.postgresql.authentication }}
    {{- if not .existingSecretName }}
      {{- if or (empty .username) (empty .password) }}
        {{- fail "Credentials to connect PostgreSQL must be provided!\nCheck .metaStore.postgresql.authentication for details!" }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}
{{- end }}

{{/*
Validate parameters of MySQL meta store.
*/}}
{{- if .Values.metaStore.mysql.enabled }}
  {{- if empty .Values.metaStore.mysql.host }}
    {{- fail "Host .metaStore.mysql.host must be set!" }}
  {{- end }}
  {{- if empty .Values.metaStore.mysql.port }}
    {{- fail "Port .metaStore.mysql.port must be set!" }}
  {{- end }}
  {{- if empty .Values.metaStore.mysql.database }}
    {{- fail "Database .metaStore.mysql.database must be set!" }}
  {{- end }}
  {{- with .Values.metaStore.mysql.authentication }}
    {{- if not .existingSecretName }}
      {{- if or (empty .username) (empty .password) }}
        {{- fail "Credentials to connect MySQL must be provided!\nCheck .metaStore.mysql.authentication for details!" }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}

{{/*
Validate parameters of S3 state store.
*/}}
{{- with .Values.stateStore.s3 }}
  {{- if .enabled }}
    {{- if empty .bucket }}
      {{- fail "Bucket .stateStore.s3.bucket must be set!" }}
    {{- end }}
    {{- if empty .region }}
      {{- fail "Region .stateStore.s3.region must be set!" }}
    {{- end }}
    {{- if and (empty .authentication.existingSecretName) (not .authentication.useServiceAccount) }}
      {{- if or (empty .authentication.accessKey) (empty .authentication.secretAccessKey)}}
        {{- fail "Either use IAM role for Service account or AccessKey/SecretAccessKey must be provided!\nCheck .stateStore.s3.authentication for details!" }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}

{{/*
Validate parameters of external MinIO state store.
*/}}
{{- if not (include "risingwave.bundle.minio.enabled" .) }}
  {{- with .Values.stateStore.minio }}
    {{- if .enabled }}
      {{- if empty .endpoint }}
        {{- fail "Endpoint .stateStore.minio.endpoint must be set!" }}
      {{- end }}
      {{- if empty .bucket }}
        {{- fail "Bucket .stateStore.minio.bucket must be set!" }}
      {{- end }}
      {{- if empty .authentication.existingSecretName }}
        {{- if or (empty .authentication.username) (empty .authentication.password) }}
          {{- fail "Username/password must be provided!\nCheck .stateStore.minio.authentication for details!" }}
        {{- end }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}

{{/*
Validate parameter of GCS state store.
*/}}
{{- with .Values.stateStore.gcs }}
  {{- if .enabled }}
    {{- if empty .bucket }}
      {{- fail "Bucket .stateStore.gcs.bucket must be set!" }}
    {{- end }}
    {{- if not .authentication.useServiceAccount }}
      {{- if and (empty .authentication.credentials) (empty .authentication.existingSecretName) }}
        {{- fail "Credentials must be provided!\nCheck .stateStore.gcs.authentication for details!" }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}

{{/*
Validate parameters of OSS state store.
*/}}
{{- with .Values.stateStore.oss }}
  {{- if .enabled }}
    {{- if empty .bucket }}
      {{- fail "Bucket .stateStore.oss.bucket must be set!" }}
    {{- end }}
    {{- if empty .region }}
      {{- fail "Region .stateStore.oss.region must be set!" }}
    {{- end }}
    {{- if not .authentication.useServiceAccount }}
      {{- if and (empty .authentication.existingSecretName) (or (empty .authentication.accessKey) (empty .authentication.secretAccessKey)) }}
        {{- fail "Either use ServiceAccount to provide credentials, or AccessKey/SecretAccessKey must be provided!\nCheck .stateStore.oss.authentication for details!" }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}

{{/*
Validate parameters of OBS state store.
*/}}
{{- with .Values.stateStore.obs }}
  {{- if .enabled }}
    {{- if empty .bucket }}
      {{- fail "Bucket .stateStore.obs.bucket must be set!" }}
    {{- end }}
    {{- if empty .region }}
      {{- fail "Region .stateStore.obs.region must be set!" }}
    {{- end }}
    {{- if and (empty .authentication.existingSecretName) (not .authentication.useServiceAccount) }}
      {{- if or (empty .authentication.accessKey) (empty .authentication.secretAccessKey) }}
        {{- fail "Either use ServiceAccount to provide credentials, or AccessKey/SecretAccessKey must be provided!\nCheck .stateStore.obs.authentication for details!" }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}

{{/*
Validate parameters of AzureBlob state store.
*/}}
{{- with .Values.stateStore.azblob }}
  {{- if .enabled }}
    {{- if empty .endpoint }}
      {{- fail "Endpoint .stateStore.azblob.endpoint must be set!" }}
    {{- end }}
    {{- if empty .container }}
      {{- fail "Container .stateStore.azblob.container must be set!" }}
    {{- end }}
    {{- if and (empty .authentication.existingSecretName) (not .authentication.useServiceAccount) }}
      {{- if or (empty .authentication.accountName) (empty .authentication.accountKey) }}
        {{- fail "Either use ServiceAccount to provide credentials, or AccountName/AccountKey must be provided!\nCheck .stateStore.azblob.authentication for details!" }}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end }}

{{/*
Validate parameters of LocalFS state store.
*/}}
{{- if .Values.stateStore.localFs.enabled }}
  {{- if empty .Values.stateStore.localFs.path }}
    {{- fail "Path .stateStore.localFs.path must be set!" }}
  {{- end }}
{{- end }}
