{{/*
Copyright RisingWave Labs
SPDX-License-Identifier: APACHE-2.0
*/}}

{{- if .Values.metaStore.mysql.enabled }}
{{- if not .Values.metaStore.mysql.authentication.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "risingwave.mysqlCredentialsSecretName" . }}
  labels:
    {{- include "risingwave.labels" . | nindent 4 }}
  {{- $annotations := (include "risingwave.annotations" . ) | trim }}
  {{- if $annotations }}
  annotations:
    {{ nindent 4 $annotations }}
  {{- end }}
stringData:
  RW_MYSQL_USERNAME: {{ .Values.metaStore.mysql.authentication.username | quote }}
  RW_MYSQL_PASSWORD: {{ .Values.metaStore.mysql.authentication.password | quote }}
{{- end }}
{{- end }}
