name: Test Charts

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
  merge_group:
    branches:
    - main
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install Helm
      uses: azure/setup-helm@v4

    - name: Install helm-unittests
      run: |
        helm plugin install https://github.com/helm-unittest/helm-unittest.git

    - name: Run Unit Tests
      run: |
        make test